const menu = [
    {
      id: 1,
      title: 'San-Andreas Theme',
      category: 'Games',
      img: './images/item-1.jpg',
      audio: './images/item-1.mp3',
      desc: `Theme song of GTA san-andreas game `,
      number: '1x',
    },
    {
      id: 2,
      title: 'Itatchi-theme',
      category: 'Anime',
      img: './images/item-2.jpg',
      audio: './images/item-2.mp3',
      desc: `Soundtrack from a famous Japanese Anime `,
      number: '2x',
    },
    {
      id: 3,
      title: 'Hoohah',
      category: 'EDM',
      img: './images/item-3.jpg',
      audio: './images/Fox Stevenson & Curbi - Hoohah.mp3',
      desc: `EDM tract by fox stevenson & Curbi `,
      number: '3x',
    },
    {
      id: 4,
      title: 'Unravel',
      category: 'Anime',
      img: './images/item-4.jpg',
      audio: './images/Unravel - Tokyo Ghoul OP [Piano].mp3',
      desc: `Tokyo Ghoul Theme song `,
      number: '4x',
    },
    {
      id: 5,
      title: 'Faded - Alan Walker',
      category: 'EDM',
      img: './images/item-5.jpg',
      audio: './images/01 Faded.mp3',
      desc: `EDM tract by Alan Walker `,
      number: '5x',
    },
    {
      id: 6,
      title: 'See you again - Charlie Puth',
      category: 'Hip-Hop',
      img: './images/item-6.jpg',
      audio: './images/Wiz_Khalifa_Feat_Charlie_Puth_-_See_You_Again.mp3',
      desc: `Famous song by singer Charlie Puth and Wiz Kalifa in the movie Fast and Furious `,
      number: '6x',
    },
    {
      id: 7,
      title: 'When i grow up - NF',
      category: 'Hip-Hop',
      img: './images/item-7.jpg',
      audio: './images/08 When I Grow Up - (SongsLover.com).mp3',
      desc: `Famous rap song by singer NF `,
      number: '7x',
    },
    {
      id: 8,
      title: 'Believer - Imagine Dragons',
      category: 'Rock',
      img: './images/item-8.jpg',
      audio: './images/09. Imagine Dragons - Believer.mp3',
      desc: `Song by a rock band 'Imagine Dragons' `,
      number: '8x',
    },
    {
      id: 9,
      title: 'Radioactive - Imagine Dragons',
      category: 'Rock',
      img: './images/item-9.jpg',
      audio: './images/01 - radioactive(2).mp3',
      desc: `Song by a rock band 'Imagine Dragons' `,
      number: '9x',
    },
    {
      id: 10,
      title: 'Wake me up - Avicii',
      category: 'EDM',
      img: './images/item-10.jpg',
      audio: './images/[1997] avicii - wake me up (cut).mp3',
      desc: `EDM tract by fox stevenson & Curbi `,
      number: '10x',
    },
    {
      id: 11,
      title: 'Sweet child O Mine - Guns N Roses',
      category: 'Rock',
      img: './images/item-11.jpg',
      audio: './images/Guns_N_Roses_-_Sweet_Child_O_Mine.mp3',
      desc: `Famous song from an American Rock band in 80s' `,
      number: '11x',
    },
    {
      id: 12,
      title: 'KillShot - Eminem',
      category: 'Hip-Hop',
      img: './images/item-12.jpg',
      audio: './images/Eminem_-_Killshot_.mp3',
      desc: `Diss Rap by Rap god Eminem `,
      number: '12x',
    },
    /*{
      id: 13,
      title: 'KillShot - Eminem',
      category: 'Jazz',
      img: './images/item-12.jpg',
      audio: './images/Eminem_-_Killshot_.mp3',
      desc: `Diss Rap by Rap god Eminem `,
      number: '13x',
    }*/
  ];
  export default menu;